### PR TITLE
Initial pass at adding site expansion feature

### PR DESCRIPTION
**Pull request by Thel89**
As detailed in https://github.com/narc0tiq/YARM/issues/18

Known issues:
- [fixed] tabs vs spaces. Oops. 
- [fixed] The corners of the buttons are no longer transparent. mspaint has failed me for the last time. :rage4: 
- [fixed] The "highlight the contents of the existing site" code doesn't actually work. I suspect that's me being bad at Lua.
- [fixed] spamming the '+' button gets lots of console output (because the new button will submit any current site, then adds the site you want to expand back to `player.current_site`. Thinking maybe we should mute console output if there's no actual change?

However, the core of it does actually work. In my test game I have YARM monitoring a single 'patch' that's actually six different patches spread over about a thousand tiles of distance.

Thoughts:
- If we have a button that allows expansion of a site, can we kick down the timer for finalizing a site to 3-5 seconds? Or maybe (this is a bigger rewrite), there shouldn't be a timer at all - smack the YARM on an ore patch and it immediately adds it, then hit the 'expand site' button and smack it on another ore patch to add that?

### CODE REVIEW

**Comment by Thel89** [comment]
OK I think I've fixed the breaking issues now:
- The "existing sites not highlighting" was me completely misunderstanding how tables in Lua work.
- Upgraded from mspaint to paint.net and did the graphics properly.
- Also fixed tabs vs spaces.

I'm still unsure about the console output for unchanged sites thing - could be unintuitive if you silently timeout.

**Comment by Thel89** [comment]
Oh, one other thing I just thought of - with this it might be possible that the same ore patch is tracked in multiple sites. Unsure if it's worth defensively coding around this (or if it's even a problem), though.

**Comment by narc0tiq** [comment]
Nah, the design makes it too hard to avoid tracking the same ore in different sites, so we just won't worry about it (and it was perfectly possible to do it before, too).

Realistically, it doesn't really matter that much, except in that the ore will be getting queried twice, so it might be a little more CPU time for the client. The (somewhat stalled) upgrade I was working on would've/will fix that by decoupling the ores from the sites.

I think I agree that we almost don't need a timer anymore, except for oil sites (which are somewhat inconvenient now, but would get _really_ inconvenient if you had to do two clicks per oil spout). This might be mitigated by having a larger search area for when you smack an ore for the first time and it has no direct (8 adjacent) neighbours of the same kind. I'd love to mostly-automatically cover most oil deposits.

I also agree that a site that hasn't changed shouldn't output any feedback console text (conversely, if it has changed, the difference should be highlighted, e.g., "Site that_site updated, now has 256,000 iron ore (+27,000).").

---

Thank you for the excellent submission; I haven't reviewed the code yet, but the *feature* is wonderful!

I have a curiosity: should we limit the extent of a site, or do we not care? In particular, I'm thinking remote viewing a site that's actually comprised of "all the iron ore on the map" isn't going to give you much value (we can probably disregard the potential performance hit of having that many ores in a single site -- that *should* only affect the rate at which its totals and estimates update). On the other hand, having that site allows you at-a-glance estimate your **total** consumption, since we don't have a "totals" filter yet.

**Comment by Thel89** [comment]
Site size limits - the reason I wrote this feature was to support extremely large, discontiguous sites - so I might be a bit biased. :) The perf impact of having a large site seems negligible (based on very quick testing, with absolutely no science behind said testing).

Not multi-tracking: About the only way you could do this would be to have a global table of sites with just ore_type + extents, and check that any time you add single ore. Agreed - not worth the effort, and potentially counterproductive until/if summary-per-ore is added.

Adding appropriate console text for expanded sites - will add that (probably not for a couple of days, though. However, the reason I'm saying the behaviour could be a bit unintuitive is if someone hits the '+' sign then gets distracted for a few seconds, the expansion will silently time out and they'll accidentally create a new site. Should the timer even apply to expanding sites? (if the timer didn't apply, would probably want a UI button for cancelling expansion)

Timer/oil sites: we *could* hardcode a wider search radius for oil, but that would probably not work particularly well for modded resources with oil-like spawn patterns (bob/dytech gems maybe?). So maybe the search radius, per-ore-type, should be in a config file somewhere? (with default of immediate-neighbour for anything not explicitly configured). Would have to be careful how the extended-range search was written to avoid duplicate tracking (and infinite loops as you track site A which sends you to B which then finds A again ...) though.

**Comment by Thel89** [comment]
Also - total consumption is available via the production screen, but I could also see the use of having partial summaries (e.g. two different iron ore fields feeding your steel production, while another fields feed your science factory and three more fields feed your rocket factory). So yeah - maybe we should add that to the documentation that multi-tracking is implicitly supported?

**Comment by Thel89** [comment]
Coming back to the console text for expanded sites - I guess one way to help the invisible timeout issue would be to have the '+' button show as clicked/highlighted until it times out. Thoughts?

**Comment by narc0tiq** [comment]
> the reason I wrote this feature was to support extremely large, discontiguous sites

Makes sense to me, and I'm glad it doesn't significantly affect performance, either. Glad to have it, then!


> have a global table of sites with just ore_type + extents

Allow me to introduce you to my friend [v0.8-dev](https://github.com/narc0tiq/YARM/blob/v0.8-dev/resmon/tracker.lua#L13) (as previously stated, a little bit stalled by my lack of attention). Instead of sites containing references to individual ore entities, they store indices from the ore tracker (which invisibly uses some trickery to store the ore data in a reasonably memory-efficient way). Notable trick: the entity references aren't persisted (avoids long save/load times -- Factorio has to do a lot of lookup to restore the proxy objects, especially if doing it at load-time for a **lot** of entities), but get reacquired on request.


> the reason I'm saying the behaviour could be a bit unintuitive is if someone hits the '+' sign then gets distracted for a few seconds, the expansion will silently time out and they'll accidentally create a new site [when they actually click].

Right, we should avoid doing that until we have some UI to show the timer itself, e.g., a progress bar. A button to cancel addition/expansion would be good, too, and then we could really do away with the timer for good (just remain in that mode until the player presses a "commit" button, maybe). I don't think that change would be so horribly cumbersome to players, and is likely more discoverable than invisible timers.


> we could hardcode a wider search radius for oil

Not specifically for oil -- just trigger it if, after the first time it searches for ore around the first tile, it doesn't find anything (i.e., the first ore is a single entity without any others orthogonally or diagonally adjacent). Oil-like resources have to match this because the oil pump is a 3x3 that will have the ore in the middle (in fact, they **must** have at least two tiles distance between them on at least one axis).


> this de-duplication is already in the current search

Yeah, it's pretty safe, I'm only concerned that a wider radius might make for a slower search -- but we're already asking the surface for "all entities of this type within this area" and getting an iterator, so the code probably doesn't change otherwise. The normal (quite dense) ores would fail the de-duplication check a bit too often for this to be a general behaviour, though (de-dup does take a bunch of CPU time).


> total consumption is available via the production screen

But not the actual ore item production rate, nor an estimate of how long until it all runs out -- consumption only tells you production rate when the system's buffers are saturated.


> maybe we should add that to the documentation

Definitely!


> one way to help the invisible timeout issue would be to have the '+' button show as clicked/highlighted until it times out

The delete button does that -- it turns red to indicate "click me again to *really* delete the site, or wait for me to turn white again to cancel". It's a little difficult for players to discover, but it suits the feel of YARM as it stands.

---

One more note: I've skimmed your code, it looks very good. I might have specific requests later, but expect them to be lint checks at most.

I wanted to ask: maybe in a separate PR you could use `reconstruct_overlay_for_existing_site` to close #10? I've wanted the ability to review the overlay since YARM was created, but it was never a priority -- now it just fell into our laps, metaphorically speaking.

**Comment by Thel89** [comment]
> Not specifically for oil -- just trigger it if, after the first time it searches for ore around the first tile, it doesn't find anything

Valid, but depending if you're using RSO or base game resource gen or mods that add custom ores, you may want to have a configurable search radius. However, this is all a moot point because I'm (currently) not game enough to attempt to rewrite the mod to remove the timer completely. :)

> maybe in a separate PR you could use reconstruct_overlay_for_existing_site to close #10

Doable - it'll be current extent only, not historical extent (untested - based on my understanding of `resmon.tick_deposit_count`, that function removes exhausted entities from the site). That good enough for now? If you're rewriting the core of the tracking in v0.8 then I'm not sure how much time is worth spending on a custom solution for historical extent tracking (I do agree it'd be cool, but would need some faffing about with the site data structure to not remove exhausted entities (leave them with a count of 0?), and appropriate changes to `resmon.tick_deposit_count` and `resmon.finish_deposit_count`). Idea: It'd be even cooler if the overlay was faded somewhat for areas that are in the historical extent but have since been exhausted. (if I'm understanding what you're doing in v0.8, historical extent tracking may not even be possible at all then because you said individual entities aren't persisted...)

On a side note, is there any way to zoom out the remote viewer so that it actually takes in the full scope of the current site? Obviously there has to be a limit somewhere, but at the moment it seems like you can add two patches of the same ore, spread by about ~100 tiles vertically, and the remote viewer will spawn in the middle of the extent and show absolutely nothing useful. Idea - rather than storing the overall extent of a site, we store the extents of each time the YARM is smacked on the ground, then allow the remote viewer to tab through views of the extents of each subsite. (Again, this is with the perspective of someone who monitors sites with a total extent size of ~1,000 tiles each way...)


Anyway, when I'm next free to spend some time on this, my plan is to:
- add a new button prototype for the 'clicked-expanding' state. (NB: as above, will keep the existing timer mechanics as they are)
- add new string for `YARM-site-expanded`. However, I see there's four locales in the mod at the moment - what happens if there's an incomplete localisation? 
- futz with code appropriately so that:
1. `YARM-site-expanded` is printed after a site is expanded.
2. `YARM-site-submitted` is printed after a new site is created only (i.e. not after a site is expanded).
3. nothing is printed after the expand button is hit but no ore was added to the site before the site was submitted.

**Comment by narc0tiq** [comment]
> it'll be current extent only, not historical extent

Yeah, either way works, and current extent is all we track. Historical extent would be cool, but too much effort at the moment.


> individual entities aren't persisted [in v0.8]

No, but persistence (what's in `global` and remains over save/load) and retention (what we remember about a site until it's deleted) are different things. We can retain the coordinates if it's worth it (my default stance is to avoid doing so, but we can), which is what we need to be able to show the overlay -- I'm not 100% certain it's worth the extra complication, but it might not be *that* complicated.


> zoom out the remote viewer

Programatically? There *is* a write-only [`player.zoom`](http://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.zoom), but I'm not at all sure how we translate coordinate bounds to a required zoom level (and we don't/can't know the player's viewport size, either).


> we store the extents of each time the YARM is smacked on the ground

Can't read that (remember, in multiplayer, remote peers only exist as conceptual entities -- they don't have a viewport), but we can store the coordinates that were smacked and center on those, cycling through multiple ones -- needs a "next camera" button. I also wouldn't mind placing an entity where the player smacks the ground, which would be the notional "camera" that is remotely monitoring.

You wanna write that into an issue, so we don't forget?


> what happens if there's an incomplete localisation?

I believe it falls back to the English locale text if only that one exists. I'm not at all sure what would happen if, say, only Hebrew existed. Probably just an "Unknown locale: locale-key" message.

---

Your plan sounds great! I look forward to seeing it in action.

**Comment by Thel89** [comment]
OK, I think that's everything. Hopefully.

**Comment by narc0tiq** [comment]
Beautiful, thanks, mate. I'll have a look at it tonight after I get home from work (in a few hours).

**Comment by narc0tiq** [comment]
Sorry about that, got caught up in AFK life things instead; I'll get to it soonest.

**Comment by narc0tiq** [comment]
Hey there, thanks so much for the work you've put in! This is amazing, and I've finally gotten a few minutes to play around with it.

---

First thought: it's _really weird_ that you can press the + and then have to go hunt down (and pick up) your resource monitor item. Maybe the button shouldn't be visible unless you have the monitor in hand (less discoverable, but also less inconvenient to the player), or perhaps you should have to press the button with monitor in hand (and message the player to tell them what to do if they just press it normally).

The biggest obvious concern: **clicking the + button can cause a noticeable pause** on a large site (1-2 seconds on my 5 million iron ore site), and it's down to the existing ore highlight. Factorio doesn't like making a lot of entities all at once, so this is why the sites build up over multiple ticks (the animation is cool, too, but that's a side-effect). Secondary mention: RSO can make some ore deposits with huge entity counts, so some players would see this pretty much immediately.

Bug report: I clicked to add to a site and then clicked the ground accidentally. This **canceled the addition, but the button is still red**. The console shows `Error: __YARM__/resmon.lua:377: attempt to index local 'site' (a nil value).`

Visual effect: it takes until the next visual refresh for a site's + to turn back white. I haven't looked at the code in detail, but can you trigger a visual update after site editing finishes?

Worth noting: clicking the + button resets the site's percentage, even if you do nothing else. This is acceptable, but there should maybe be a mention in the Readme.

---

this is awesome

I am otherwise impressed by how well this huge (by extents) site is working out. Sure, it takes a couple of refresh cycles to update its stats, but it does update them regularly enough I'm not going to complain. And I **love** being able to keep adding to it.

This is great!

**Comment by Thel89** [comment]
Existing highlight: should we make this a mod config option? Or tweak it somehow so it builds up over some number of ticks? Thinking maybe something like (pseudo code):
```
on each tick:
if temp_list is empty and entity_table is not all highlighted, pick an entity from entity_table into temp_list
for each entity in temp_list:
- highlight entity
- add immediate neighbours to temp_list
```
Which, assuming I can logic, should mean each ore deposit should be highlighted sequentially (but with no guarantee of which deposit gets chosen first) - the other option is we store a list of places where the YARM has been smacked with each site and radiate out from there (or if we ever put the camera/multiple views thing in, the cameras would be a natural place to highlight from). That's probably more natural, but a bit more work - and will also potentially fall apart when sites get near to exhaustion (because then the YARM smack site is empty ground, rather than being a resource). 


**Bug report:** will investigate sometime over the weekend.


**Vis fx:** yeah, we can force an update for all players in `submit_site`. I should probably pull that out into it's own function because it's called in four or five places already.


**Percentage reset:** I can probably work around that, but it's going to be a bit complicated. Actually ... it's because I call `resmon.finalize_site` in `resmon.on_click.expand_site`, which I'm fairly sure is mostly redundant - we don't need to reset stats or recalculate the bounding box when the GUI button is clicked. Should just be able to get away with setting the `finalizing` state and the `finalizing_since` tick count.

**Comment by narc0tiq** [comment]
> each ore deposit should be highlighted sequentially (but with no guarantee of which deposit gets chosen first)

Right, we don't really care about order necessarily, we just need to be building up the entities gradually (at whatever rate they get built up during ore discovery).


> and will also potentially fall apart when sites get near to exhaustion

That's the biggest reason to avoid it, really. The hybrid you've shown, that picks an entity from the site's list and radiates out from there using normal ore discovery, is pretty good. You might even be able to use the ore discovery code directly with some refactoring.

In v0.8 this will probably even start with the earliest discovered ore still existing, because the site ore list will be a simple array.


> Should just be able to get away with setting the `finalizing` state and the `finalizing_since` tick count.

I think so, yes. Give it a try, see if it helps. I imagine it'll still reset if you do make changes, but then at that point, the player should be expecting it.

---

One other thing I just thought of: what happens when two players try to expand the same site at the same time? With two sub-cases: either they're expanding it into the same new patch, or into different patches.

You should look me up (Narc0tiq) on the Factorio IRC (irc://irc.esper.net/#factorio) and see if we can get together and mess with it in multiplayer some time.

**Comment by Thel89** [comment]
> One other thing I just thought of: what happens when two players try to expand the same site at the same time?

Huh, that's a fun one. Best guess - the UI sync is forced in all the right places (I think) so they'll both be expanding the same site, and either:
- the first one to submit will write the new site data into force_data, and the second one to attempt to submit will either get an error or silently fail; or
- the first one to submit will write their version of the site into force_data, and the second one will overwrite the same site. 

I'm picking the first option as the more likely one but I'm not 100% certain. 

> Bug report: I clicked to add to a site and then clicked the ground accidentally. **This canceled the addition, but the button is still red.**

Resolved. Turns out I didn't actually test as thoroughly as I thought I did. :flushed:

> Worth noting: clicking the + button resets the site's percentage, even if you do nothing else.

Resolved. Removed the call to `resmon.finalize_site` in `resmon.on_click.expand_site` and instead just set the finalizing state and time directly. 

> Visual effect: it takes until the next visual refresh for a site's + to turn back white. I haven't looked at the code in detail, but can you trigger a visual update after site editing finishes?

Resolved. There's a new function `resmon.update_force_members_ui`', too (because I was doing `for _, p in pairs(player.force.players) do resmon.update_ui(p) end` in six different places).

So, the only open issue is making the highlighting not-blocking, plus maybe the UX of needing to find your YARM after pressing the + button. I guess the other option there would be to bring the player's YARM into their cursor (assuming they have a YARM and their cursor is empty).

**Comment by narc0tiq** [comment]
> I'm picking the first option as the more likely one but I'm not 100% certain.

I'd guess at the latter, actually, because the key (the force, and the site name) is relatively stable (incidentally, this suggests we can copy a site if one player renames it while another is expanding it; I do not consider this an issue, necessarily, but it should not crash).


> Turns out I didn't actually test as thoroughly as I thought I did.

Yup, that happens. Er, I mean, *cough*, I have no idea *cough* how that could possibly work. *cough* :angel: 


> I guess the other option there would be to bring the player's YARM into their cursor (assuming they have a YARM and their cursor is empty).

Yes, I hadn't considered it, but that's a fair point.

On that note, an "add site" button could do the same just for general adding. And then, you know, we could just remove the recipe for the resource monitor item and just spawn one when the player needs it (and discard it thereafter). And I've just talked myself into a largish UX change that I'm going to go ahead and shove into a different issue.

**Comment by Thel89** [comment]
> So, the only open issue is making the highlighting not-blocking

I've been playing around with various ways of handling this - and while I *could* make `scan_current_site` generic enough to handle either adding a new site or re-overlaying an existing site, I worry it's going to make the code a bit obscure - would have to make parameters for both the action taken (in the current instance, that's `add_single_entity`) and potentially the list of things to do.

Question: What should happen if we have a highlight running in the background, and the player tries to extend the site?

Secondly, what happens if we have a site that takes longer than 10 seconds to highlight? Should we not start the timer until the highlight is finished?

**Comment by narc0tiq** [comment]
> I worry it's going to make the code a bit obscure

Yeah, I can see that; don't worry about it. Just reuse whatever makes sense to, if anything.


> What should happen if we have a highlight running in the background, and the player tries to extend the site?

Either it goes into the queue and will get processed as soon as the highlighting is done, or (if at all possible), it gets done in parallel. Depending on how the highlight works, working in parallel may or may not be doable. If so, that affects the below.


> Secondly, what happens if we have a site that takes longer than 10 seconds to highlight? Should we not start the timer until the highlight is finished?

Think you answered your own question there -- wait for the highlight to finish before running the timer. If it's possible to run highlight and discovery in parallel, as above, then the timer really shouldn't start until after both are done (currently it's keyed to discovery only).

**Comment by Thel89** [comment]
OK, took a stab at it. It's probably fairly buggy, but works fine on my machine. :innocent:  

Relevant notes:
- Re-adding an overlay to an existing site should run in parallel with any expansions you click.
- The timer doesn't start until the site is fully highlighted.
- Haven't tested what happens if you don't have a YARM in your inventory when you click the + button
- I did, accidentally, find out that you can robot-place (by shift-click) a YARM and it will actually be constructed as an entity. Fairly sure I didn't introduce that behaviour, though.

**Comment by narc0tiq** [comment]
> OK, took a stab at it.

Yes! That's excellent; I have to try it out in as evil a circumstance as I can manage, but if it works, we've got us a (potential) winner.


> I did, accidentally, find out that you can robot-place (by shift-click) a YARM and it will actually be constructed as an entity. Fairly sure I didn't introduce that behaviour, though.

I'm quite certain you're right; I'll try to do it on a clean copy of YARM and write it up as a separate issue. Surprised nobody reported it before -- you'd think at least 10 people would've been holding shift at the wrong moment (so at least one would've reported it).

**Comment by narc0tiq** [comment]
Now I get to play with it, hooray! Dis gon b gud.

First order of business: tell the player they can't add to a site when they don't have a resource monitor at all. Likewise, tell them if something goes wrong with putting the resource monitor in their hand. In both cases, avoid starting the add-to-site process.

Secondly, the right thing happens when I try to add an already-added (but not yet highlighted) ore to the same site. However, I'm getting reports that `Site "SW 32" updated, now has 2,046,979 Iron ore (+-48).` (the obvious reason being that the miners working it reduced it by 48 while the addition process was ongoing). I'm okay with getting the report, but I'm not okay with the "+-".

Interesting behaviour: if you delete a site while the adding process is ongoing, the site will be recreated when the addition finalizes. In this case, there will be no feedback to the player that anything happened (other than the site showing up again in their YARM).

Otherwise, this is damn near perfect -- making this 12 million ore deposit has never been easier:
12 million dollars!

**Comment by Thel89** [comment]
> First order of business: tell the player they can't add to a site when they don't have a resource monitor at all. Likewise, tell them if something goes wrong with putting the resource monitor in their hand. In both cases, avoid starting the add-to-site process.

Can do. Will need to rearrange various bits of code, though. (I spent like four hours getting the background overlay regeneration working, and about 5 minutes doing the YARM-to-cursor bit, so one of them is likely a bit more polished than the other)

> Secondly, the right thing happens when I try to add an already-added (but not yet highlighted) ore to the same site. However, I'm getting reports that Site "SW 32" updated, now has 2,046,979 Iron ore (+-48). (the obvious reason being that the miners working it reduced it by 48 while the addition process was ongoing). I'm okay with getting the report, but I'm not okay with the "+-".

I'll probably change the logic here so that the site is only listed as having expanded when an ore entity is actually added to the site (currently a site is listed as having expanded as soon as you smack the YARM on a resource). I'll also check the `amount_added` and only put a '+' in front if it's actually positive.

> Interesting behaviour: if you delete a site while the adding process is ongoing, the site will be recreated when the addition finalizes. In this case, there will be no feedback to the player that anything happened (other than the site showing up again in their YARM).

Also fixable, although as I think about it more it may be slightly more complicated than I thought. Essentially, we need to clear `player_data.current_site` if it's the same site as we're currently deleting. (Don't want to always clear current_site, because we could be deleting a different site to the one we're currently expanding...)

**Comment by narc0tiq** [comment]
> four hours getting the background overlay regeneration working, and about 5 minutes doing the YARM-to-cursor bit

That sounds about right; one of these is much trickier than the other.


> only listed as having expanded when an ore entity is actually added to the site

I don't know, I'm pretty okay with YARM telling me the difference from the old total (and resetting the 100% point can be a desirable feature). Just doing the '+' in back-end code rather than locale should be enough.


>> delete a site while the adding process is ongoing
>
> Also fixable, although as I think about it more it may be slightly more complicated than I thought.

I'm not terribly concerned about it, so you could also just ignore it altogether. It's well within the realm of acceptable behaviour.


> it'll be a couple days

Not a problem, I've only really poked at this while at work in the first place -- it'll keep another few days.

**Comment by narc0tiq** [comment]
Hey, that's cool! My CI integration actually detected something! I'm sure you weren't intending to test that, but it's the first time I've gotten feedback from it that it does work :+1:

**Comment by Thel89** [comment]
> Hey, that's cool! My CI integration actually detected something! I'm sure you weren't intending to test that, but it's the first time I've gotten feedback from it that it does work :+1:

As the following commit implies, I should probably test locally before pushing. :unamused: 

Er I mean yes I totally intended to test your CI pipeline and it passed! :confetti_ball: 

On a related note - do you want me to squash some of these commits together, or are you not worried about a bunch of fixup commits in your history?

Anyway, I've fixed the display issue (around '+-48') and improved the messaging around the pull-YARM-to-hand functionality. I think I'm going to leave "only listing a site as expanded when a new ore is added to it" and "properly delete a site if you delete it while the expansion timer is going" as won't-fix (for now at least), can always revisit them later.

**Comment by narc0tiq** [comment]
> do you want me to squash some of these commits together, or are you not worried about a bunch of fixup commits in your history?

I honestly don't mind them at all; if you *really* want to, you can prettify, but it's purely up to your comfort level.


> leave "only listing a site as expanded when a new entity is added to it" and "properly delete a site if you delete it while the expansion timer is going" as won't-fix (for now at least), can always revisit them later.

Agreed, and many thank-yous!


I'm going to get this merged in after I give it a new test (and a style/lint/nitpicking pass around the code). You've done tremendously fine work here, thanks.

**Comment by narc0tiq** [comment]
Sorry for the delay; as you've noticed, this is now merged. I hope you'll have time for more contributions in future, and thanks again.

**Pull request merged**
