### PR TITLE
Fix for #127

### LINKED ISSUE #127: Mining Speed / ETA is not Accurate
How To Fix:

File: resmon.lua
Line: 641
Fix: Change "if delta_ore_since_last_update > 0 then " to "if delta_ore_since_last_update ~= 0 then"

"delta_ore_since_last_update" is always 0 or a negative number, thus this condition is never true.

### PR DESCRIPTION
**Pull request by Kingdud**
The code included does two things:
1. It fixes #127 
2. It changes how ore_per_minute is calculated. It keeps a circular list of the last 10 changes to the field size and averages them out, then factors in the idle time between the most recent update, the now, and the oldest data in the array to give an accurate use rate on 'pulsed' (on for a bit, off for a bit) fields.
 
So, say the array had 10 minutes of data from a field that was 100% in use. But then all belts filled after 10 minutes and it went idle for 10 minutes. The code would say "10 minutes passed between the oldest snapshot of the field and the most recent change." and it would also realize 10 minutes had passed between the last snapshot and right now. It would thus compute the average ore rate for the 10 minute the field was running (say 3000 ore/min) and then decrease that by the factor of idle time (10m of data, 10m of idle = 50% decrease to mining rate). So it would report 1500 ore/min as the result to be displayed.

I have lots of comments in the code explaining how and why things are done. I need to test it more on my end to ensure there are no more weird bugs. But for now, I can add a field, remove a field, and just have fields mine all without issue. The one 'weird bit' is that until a field has been mining for at least 20 seconds (with default settings) it will not display a correct mining rate. This is because I need at least two snapshots to calculate a mining rate, and we only check for changes every 10 seconds (at least on my map).

### CODE REVIEW

**Comment by dturner42** [comment]
It seems you are working on this again @narc0tiq - Can this fix be merged in if it resolves issue #127?

**Comment by narc0tiq** [comment]
Well, I've just returned to playing a bit of Factorio and so I've been trying this patch for the last couple of days. It feels fairly reliable, so I'm going to merge it in and call it good.

**Comment by narc0tiq** [comment]
Sorry this took so long, I haven't been playing Factorio for the last, um... two years or so, so YARM and EvoGUI weren't really something I was paying much attention to.

**Comment by narc0tiq** [comment]
NB: There have been [multiple reports of save file corruption](https://mods.factorio.com/mod/YARM/discussion/624a92cb45634948ba15ab5e) (including #145) with this patch; I'm going to go ahead and revert it, but will attempt to reinclude it later. From testing, it seems that an ore site that's idle enough to generate "n/m" as the ore-per-minute report is what causes Factorio to believe the save to be corrupted -- where "n" stands for "NaN", aka Not a Number. Mining a single piece of ore is enough to prevent the corruption, but obviously this can't be left this way.

**Pull request merged**
